Revert "libcutils: Fix aliasing violations"
This reverts commit 826d75fb6dcefe8a6c6d4d54a7d215553945812a.
Breaking build with 4.2

bionic/libc/include/string.h:105:33: error: call to '__memcpy_dest_size_error' declared with attribute error: memcpy called with size bigger than destination
bionic/libc/include/string.h:109:32: error: call to '__memcpy_src_size_error' declared with attribute error: memcpy called with size bigger than source

Change-Id: I777e5f5cd87fb972c833ef6bd81b23cd29878e9b

Conflicts:
	adb/Android.mk
	libnetutils/ifc_utils.c